### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by Aldikitta** [LinX64/CoinCap#11]
Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.4.1'] was not found in any of the following sources:

**Comment by LinX64** [comment]
Hello, and thanks for your report.

I am constantly adding improvements and making changes to this repository, so please do a pull first, and then try to rebuild the project.

You can also count on -> `Menu -> File -> Invalidate caches` as the last resort.

As a note, as you can see the build job/task was able to pass on the workflow, so doing a pull request will solve the issue.

**Comment by LinX64** [comment]
Hey! @Aldikitta 

Could you please confirm that you were able to resolve the issue?

**Comment by Aldikitta** [comment]
it's fix
